# .goreleaser.yml
version: 2
project_name: terraform-graphx

builds:
  - id: terraform-graphx
    main: ./main.go
    binary: terraform-graphx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: terraform-graphx
    builds:
      - terraform-graphx
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  body: |
    {{ .Title }}

    {{ .Changelog }}